presets:
- env:
  # to prevent ginkgo-e2e.sh from using the cluster/eks functions
  - name: KUBERNETES_CONFORMANCE_TEST
    value: yes
  - name: KUBERNETES_CONFORMANCE_PROVIDER
    value: eks
  # configure worker node private key path to "~/.ssh/kube_aws_rsa"
  # see https://godoc.org/k8s.io/kubernetes/test/e2e/framework#GetSigner
  - name: AWS_SSH_KEY
    value: kube_aws_rsa
  # URL to download the latest 'aws-k8s-tester' release
  - name: AWS_K8S_TESTER_EKS_AWS_K8S_TESTER_DOWNLOAD_URL
    value: https://github.com/aws/aws-k8s-tester/releases/download/0.2.1/aws-k8s-tester-0.2.1-linux-amd64
  - name: AWS_K8S_TESTER_EKS_AWS_K8S_TESTER_DOWNLOAD_PATH
    value: /tmp/aws-k8s-tester/aws-k8s-tester
  - name: AWS_K8S_TESTER_EKS_KUBECTL_DOWNLOAD_PATH
    value: /tmp/aws-k8s-tester/kubectl
  - name: AWS_K8S_TESTER_EKS_KUBECONFIG_PATH
    value: /tmp/aws-k8s-tester/kubeconfig
  - name: KUBECONFIG
    value: /tmp/aws-k8s-tester/kubeconfig
  # upstream "kubernetes/kubernetes/hack/ginkgo-e2e.sh" requires this via "cluster/kubectl.sh"
  - name: KUBECTL
    value: "/tmp/aws-k8s-tester/kubectl --kubeconfig=/tmp/aws-k8s-tester/kubeconfig"
  - name: AWS_K8S_TESTER_EKS_AWS_IAM_AUTHENTICATOR_DOWNLOAD_PATH
    value: /tmp/aws-k8s-tester/aws-iam-authenticator
  # test mode is either "embedded" or "aws-cli" ("embedded" uses native AWS Go client, "aws-cli" will use 'aws')
  - name: AWS_K8S_TESTER_EKS_TEST_MODE
    value: "embedded"
  # duration to wait before destroying EKS cluster, useful to add wait time before collecting AWS ALB access logs
  - name: AWS_K8S_TESTER_EKS_WAIT_BEFORE_DOWN
    value: 1m0s
  # 'true' to destroying all AWS resources when it calls "Down"
  - name: AWS_K8S_TESTER_EKS_DOWN
    value: "true"
  # 'true' to assign worker nodes across all available subnets
  - name: AWS_K8S_TESTER_EKS_ENABLE_WORKER_NODE_HA
    value: "true"
  # 'true' to open port 22 in security group, and enable SSH for log dumper
  - name: AWS_K8S_TESTER_EKS_ENABLE_NODE_SSH
    value: "true"
  # 'true' to enable S3 Access Logs and AWS ALB Access Logs
  # use it for debug, dump cluster log already handles log artifacts
  - name: AWS_K8S_TESTER_EKS_LOG_ACCESS
    value: "false"
  # 'true' to upload 'aws-k8s-tester' logs to S3 buckets, in addition to log dumper
  # use it for debug, dump cluster log already handles log artifacts
  - name: AWS_K8S_TESTER_EKS_UPLOAD_TESTER_LOGS
    value: "false"
  # 'true' to upload worker node logs to S3, in addition to log dumper
  # use it for debug, dump cluster log already handles worker node logs
  - name: AWS_K8S_TESTER_EKS_UPLOAD_WORKER_NODE_LOGS
    value: "false"
  # "2" to add S3 bucket lifecycle of 2 days; let bucket be deleted in 2 days
  - name: AWS_K8S_TESTER_EKS_UPLOAD_BUCKET_EXPIRE_DAYS
    value: "2"
  # worker node auto-scaling group minimum number of nodes
  - name: AWS_K8S_TESTER_EKS_WORKER_NODE_ASG_MIN
    value: "1"
  # worker node auto-scaling group maximum number of nodes
  - name: AWS_K8S_TESTER_EKS_WORKER_NODE_ASG_MAX
    value: "1"
  # 'true' to enable debug level logs
  - name: AWS_K8S_TESTER_EKS_LOG_DEBUG
    value: "false"
  # 'true' to create AWS ALB
  - name: AWS_K8S_TESTER_EKS_ALB_ENABLE
    value: "false"
  # AWS test account credential mounted path, required for AWS API call
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: /etc/eks-aws-credentials/eks-aws-credentials
  labels:
    preset-kubernetes-e2e-aws-eks-common: "true"
  volumeMounts:
  - mountPath: /etc/eks-aws-credentials
    name: eks-aws-credentials
    readOnly: true
  volumes:
  - name: eks-aws-credentials
    secret:
      secretName: eks-aws-credentials

- env:
  # configure EKS Kubernetes version
  - name: AWS_K8S_TESTER_EKS_KUBERNETES_VERSION
    value: "1.11"
  # Amazon EKS-optimized AMI (non-GPU, https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html)
  - name: AWS_K8S_TESTER_EKS_WORKER_NODE_AMI
    value: ami-094fa4044a2a3cf52
  # URL to download 'kubectl', required for 'kubectl' calls to EKS (https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html)
  # TODO: use upstream 'kubectl'
  - name: AWS_K8S_TESTER_EKS_KUBECTL_DOWNLOAD_URL
    value: https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.5/2018-12-06/bin/linux/amd64/kubectl
  # URL to download 'aws-iam-authenticator', required for 'kubectl' calls to EKS (https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html)
  - name: AWS_K8S_TESTER_EKS_AWS_IAM_AUTHENTICATOR_DOWNLOAD_URL
    value: https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.5/2018-12-06/bin/linux/amd64/aws-iam-authenticator
  # worker node EC2 instance type
  - name: AWS_K8S_TESTER_EKS_WORKER_NODE_INSTANCE_TYPE
    value: m3.xlarge
  labels:
    preset-kubernetes-e2e-aws-eks-1-11: "true"
