presubmits:
  kubernetes/org:
  - name: pull-org-test-all
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/cloud-builders/bazel
        command:
        - bazel
        args:
        - test
        - //...
  - name: pull-org-verify-all
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/cloud-builders/bazel
        command:
        - ./hack/verify-all.sh
