apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sinker
  labels:
    app: sinker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sinker
    spec:
      containers:
      - name: sinker
        args:
        - --build-cluster=/etc/cluster/cluster
        image: gcr.io/k8s-prow/sinker:v20180521-f8caf9625
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - mountPath: /etc/cluster
          name: cluster
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
      - name: cluster
        secret:
          secretName: build-cluster
