presubmits:
  kubernetes-csi/csi-driver-host-path:
  - name: pull-sig-storage-csi-driver-host-path
    always_run: false
    decorate: true
    skip_report: false
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      # We need this image because it has Docker in Docker and go
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190220-615bdbe2e-master
        command:
        - runner.sh
        args:
        - ./.prow.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2000m
