periodics:
- name: ci-cluster-api-build
  interval: 1h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/cluster-api:v20190114-652973a54
      args:
      - "--repo=sigs.k8s.io/cluster-api"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--scenario=execute"
      - "--"
      - "./scripts/ci-build.sh"
- name: ci-cluster-api-test
  interval: 1h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/cluster-api:v20190114-652973a54
      args:
      - "--repo=sigs.k8s.io/cluster-api"
      - "--root=/go/src"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--scenario=execute"
      - "--"
      - "./scripts/ci-test.sh"
