periodics:
  - name: ci-cluster-api-provider-vsphere-ova-e2e
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
      preset-cluster-api-provider-vsphere-e2e-creds: "true"
    decorate: true
    interval: 24h
    extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-vsphere
      base_ref: master
      path_alias: sigs.k8s.io/cluster-api-provider-vsphere
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190220-615bdbe2e-master
        command:
        - runner.sh
        args:
        - ./scripts/e2e/e2e.sh
        - "ova"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
