presubmits:
  kubernetes-sigs/aws-ebs-csi-driver:
  - name: pull-aws-ebs-disk-csi-driver-verify
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20181105-66d3bcb98-master
        command:
        - runner.sh
        args:
        - hack/verify-all.sh
  - name: pull-aws-ebs-csi-driver-unit
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20181105-66d3bcb98-master
        command:
        - runner.sh
        args:
        - make
        - test
  - name: pull-aws-ebs-csi-driver-sanity
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20181105-66d3bcb98-master
        command:
        - runner.sh
        args:
        - make
        - test-sanity
