.minikube_small: &minikube_small
  resources:
    requests:
      cpu: 2900m
      memory: 8Gi

periodics:
- name: cert-manager-e2e-v1-7
  interval: 12h
  agent: kubernetes
  labels:
    cert-manager-cloudflare-svc-acct: "true"
    preset-service-account: "true"
    libvirt-socket: "true"
    minikube-support: "true"
    minikube-small: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    # Note: this is not supported yet by prow PodSpec, taint temporary removed
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: gcr.io/jetstack-build-infra/minikube-in-go-v1.7.15:0.14
      args:
      - "--repo=github.com/jetstack/cert-manager=master"
      - "--root=/go/src"
      - "--upload=gs://jetstack-logs/logs"
      - "--clean"
      <<: *minikube_small
      securityContext:
        privileged: true

- name: cert-manager-e2e-v1-8
  interval: 12h
  agent: kubernetes
  labels:
    cert-manager-cloudflare-svc-acct: "true"
    preset-service-account: "true"
    libvirt-socket: "true"
    minikube-support: "true"
    minikube-small: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    # Note: this is not supported yet by prow PodSpec, taint temporary removed
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: gcr.io/jetstack-build-infra/minikube-in-go-v1.8.10:0.14
      args:
      - "--repo=github.com/jetstack/cert-manager=master"
      - "--root=/go/src"
      - "--upload=gs://jetstack-logs/logs"
      - "--clean"
      <<: *minikube_small
      securityContext:
        privileged: true
