# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - jetstack/cert-manager
  - jetstack/kube-lego
  - jetstack/test-infra
  - jetstack/navigator
  - jetstack/tarmak
  - jetstack/okta-kubectl-auth
  - jetstack/puppet-module-aws_ebs
  - jetstack/puppet-module-calico
  - jetstack/puppet-module-etcd
  - jetstack/puppet-module-kubernetes
  - jetstack/puppet-module-kubernetes_addons
  - jetstack/puppet-module-prometheus
  - jetstack/puppet-module-vault_client
  - jetstack/puppet-module-tarmak
  - jetstack/vault-helper
  - jetstack/vault-unsealer
  - jetstack/vault-plugin-auth-templated-aws
  trusted_org: jetstack

blunderbuss:
  # Only request a review from 1 reviewer
  request_count: 1

external_plugins:
  jetstack/kube-lego:
  - name: needs-rebase
  jetstack/navigator:
  - name: needs-rebase
  jetstack/cert-manager:
  - name: needs-rebase
  jetstack/tarmak:
  - name: needs-rebase

# heart:
#   adorees:
#   - k8s-merge-robot

# slack:
#   mergewarnings:
#   - repos:
#     - kubernetes/kubernetes
#     channels:
#     - kubernetes-dev
#     whitelist:
#     - k8s-merge-robot

milestonestatus:
  # You can curl the following endpoint in order to determine the github ID of your team
  # responsible for maintaining the milestones:
  # curl -H "Authorization: token <token>" https://api.github.com/orgs/<org-name>/teams
  maintainers_id: 2462700

config_updater:
  config_file: prow/config.yaml
  plugin_file: prow/plugins.yaml

plugins:

  jetstack/test-infra:
  - trigger
  - config-updater
  - shrug
  - lgtm
  - approve
  - size
  - wip
  - lifecycle
  - reopen
  - assign
  - hold
  - label


  jetstack/cert-manager:
  - docs-no-retest
  - trigger
  - release-note
  - blunderbuss
  - assign
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - approve
  - skip
  - milestonestatus
  - lifecycle
  - size
  - yuks
  - wip
  - shrug

  jetstack/kube-lego:
  - docs-no-retest
  - trigger
  - assign
  - lifecycle
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/navigator:
  - docs-no-retest
  - trigger
  - release-note
  - blunderbuss
  - assign
  - lifecycle
  - reopen
  - golint
  - heart
  - hold
  - label
  - approve
  - lgtm
  - milestonestatus
  - size
  - yuks
  - wip
  - shrug

  jetstack/tarmak:
  - docs-no-retest
  - trigger
  - release-note
  - assign
  - blunderbuss
  - lifecycle
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - approve
  - milestonestatus
  - size
  - yuks
  - wip
  - shrug

  jetstack/okta-kubectl-auth:
  - docs-no-retest
  - trigger
  - release-note
  - assign
  - blunderbuss
  - lifecycle
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - approve
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-aws_ebs:
  - docs-no-retest
  - trigger
  - assign
  - lifecycle
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-calico:
  - docs-no-retest
  - trigger
  - assign
  - lifecycle
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-etcd:
  - docs-no-retest
  - trigger
  - assign
  - lifecycle
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-kubernetes:
  - docs-no-retest
  - trigger
  - assign
  - lifecycle
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-kubernetes_addons:
  - docs-no-retest
  - trigger
  - assign
  - lifecycle
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-prometheus:
  - docs-no-retest
  - trigger
  - assign
  - lifecycle
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-tarmak:
  - docs-no-retest
  - trigger
  - assign
  - lifecycle
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/puppet-module-vault_client:
  - docs-no-retest
  - trigger
  - assign
  - lifecycle
  - reopen
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug

  jetstack/vault-helper:
  - docs-no-retest
  - trigger
  - release-note
  - assign
  - blunderbuss
  - lifecycle
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - approve
  - size
  - yuks
  - wip
  - shrug

  jetstack/vault-unsealer:
  - docs-no-retest
  - trigger
  - release-note
  - assign
  - blunderbuss
  - lifecycle
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - approve
  - size
  - yuks
  - wip
  - shrug

  jetstack/vault-plugin-auth-templated-aws:
  - docs-no-retest
  - trigger
  - release-note
  - assign
  - blunderbuss
  - lifecycle
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - approve
  - size
  - yuks
  - wip
  - shrug
