presubmits:

  jetstack/vault-helper:
  - name: vault-helper-quick-verify
    always_run: true
    skip_report: false
    context: vault-helper-quick-verify
    max_concurrency: 2
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/jetstack-build-infra/gcloud-in-go:0.10
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify|)( \\[.+\\])?$"
    rerun_command: "/test verify"

  jetstack/vault-plugin-auth-templated-aws:
  - name: vault-plugin-auth-templated-aws-quick-verify
    always_run: true
    skip_report: false
    context: vault-plugin-auth-templated-aws-quick-verify
    max_concurrency: 2
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/jetstack-build-infra/gcloud-in-go:0.10
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify|)( \\[.+\\])?$"
    rerun_command: "/test verify"

  jetstack/vault-unsealer:
  - name: vault-unsealer-quick-verify
    always_run: true
    skip_report: false
    context: vault-unsealer-quick-verify
    max_concurrency: 2
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/jetstack-build-infra/gcloud-in-go:0.10
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify|)( \\[.+\\])?$"
    rerun_command: "/test verify"

  jetstack/okta-kubectl-auth:
  - name: okta-kubectl-auth-quick-verify
    always_run: true
    skip_report: false
    context: okta-kubectl-auth-quick-verify
    max_concurrency: 2
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/jetstack-build-infra/gcloud-in-go:0.10
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify|)( \\[.+\\])?$"
    rerun_command: "/test verify"
