postsubmits:
  kubernetes/org:
  - name: post-org-peribolos
    cluster: test-infra-trusted
    decorate: true
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel
        imagePullPolicy: Always
        command:
        - bazel
        args:
        - run
        - //admin:update
        - --
        - --github-token-path=/etc/github-token/oauth
        - --confirm
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
      volumes:
      - name: github
        secret:
          secretName: oauth-token
  kubernetes/test-infra:
  - name: post-test-infra-deploy-prow
    cluster: test-infra-trusted
    decorate: true
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-bazel:v20181107-d88dbbf
        command:
        - prow/deploy.sh
        args:
        - --confirm
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /creds/service-account.json
        volumeMounts:
        - name: creds
          mountPath: /creds
      volumes:
      - name: creds
        secret:
          secretName: deployer-service-account

  - name: post-test-infra-push-prow
    cluster: test-infra-trusted
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-bazel:v20181107-d88dbbf
        command:
        - prow/bump.sh
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /creds/service-account.json
        volumeMounts:
        - name: creds
          mountPath: /creds
      volumes:
      - name: creds
        secret:
          secretName: pusher-service-account

periodics:
- interval: 24h
  name: ci-org-peribolos
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: org
    base_ref: master
  spec:
    containers:
    - image: launcher.gcr.io/google/bazel
      imagePullPolicy: Always
      command:
      - bazel
      args:
      - run
      - //admin:update
      - --
      - --github-token-path=/etc/github-token/oauth
      - --confirm
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
    volumes:
    - name: github
      secret:
        secretName: oauth-token
